<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Statistics Lab | Green Teams R Lab</title>
  <meta name="description" content="A Lab with Examples for getting started using R." />
  <meta name="generator" content="bookdown 0.23 and GitBook 2.6.7" />

  <meta property="og:title" content="Statistics Lab | Green Teams R Lab" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="A Lab with Examples for getting started using R." />
  <meta name="github-repo" content="roqarr" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Statistics Lab | Green Teams R Lab" />
  
  <meta name="twitter:description" content="A Lab with Examples for getting started using R." />
  



<meta name="date" content="2022-06-09" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="stats.html"/>

<script src="libs/header-attrs-2.10/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.5.3/htmlwidgets.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/proj4-2.6.2/proj4.min.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.0.4.1/leaflet.js"></script>
<script src="libs/leaflet-providers-1.9.0/leaflet-providers_1.9.0.js"></script>
<script src="libs/leaflet-providers-plugin-2.0.4.1/leaflet-providers-plugin.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./index.html">Green Teams<br>R Lab</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>About</a></li>
<li class="chapter" data-level="" data-path="download.html"><a href="download.html"><i class="fa fa-check"></i>Download R</a></li>
<li class="chapter" data-level="" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i>Introduction to R</a></li>
<li class="chapter" data-level="" data-path="intro-lab.html"><a href="intro-lab.html"><i class="fa fa-check"></i>Intro to R Lab</a></li>
<li class="chapter" data-level="" data-path="data.html"><a href="data.html"><i class="fa fa-check"></i>Working with Data</a></li>
<li class="chapter" data-level="" data-path="data-lab.html"><a href="data-lab.html"><i class="fa fa-check"></i>Data Lab</a></li>
<li class="chapter" data-level="" data-path="graphs.html"><a href="graphs.html"><i class="fa fa-check"></i>Graphs in R</a></li>
<li class="chapter" data-level="" data-path="graph-lab.html"><a href="graph-lab.html"><i class="fa fa-check"></i>Graphing Lab</a></li>
<li class="chapter" data-level="" data-path="stats.html"><a href="stats.html"><i class="fa fa-check"></i>Statistics in R</a></li>
<li class="chapter" data-level="" data-path="statistics-lab.html"><a href="statistics-lab.html"><i class="fa fa-check"></i>Statistics Lab</a></li>
<li class="divider"></li>
<li><a href="https://www.montclair.edu/pseg-sustainability-institute/"><img src="./psegiss.jpg" width=100% alt="MSU Logo"></a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"><p>Green Teams R Lab</p></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="statistics-lab" class="section level1">
<h1>Statistics Lab</h1>
<div id="example-data-set-mtcars-2" class="section level2">
<h2>Example Data Set <code>mtcars</code></h2>
<p>Like in the introduction lab, we will be using the <code>mtcars</code> data set to learn how to graph data in R.
Below is an excerpt of mtcars, displaying the first 6 cars in the list. The columns have been renamed, and some columns have been removed for ease of presentation.</p>
<table>
<caption><span id="tab:unnamed-chunk-85">Table 8: </span>Top Six Fuel Efficient 4-Cylinder Engines</caption>
<colgroup>
<col width="14%" />
<col width="17%" />
<col width="20%" />
<col width="29%" />
<col width="17%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Make and Model</th>
<th align="center">Miles per Gallon</th>
<th align="center">Number of Cylinders</th>
<th align="center">Displacement in Cubic Inches</th>
<th align="center">Gross Horsepower</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Toyota Corolla</td>
<td align="center">33.9</td>
<td align="center">4</td>
<td align="center">71.1</td>
<td align="center">65</td>
</tr>
<tr class="even">
<td align="left">Fiat 128</td>
<td align="center">32.4</td>
<td align="center">4</td>
<td align="center">78.7</td>
<td align="center">66</td>
</tr>
<tr class="odd">
<td align="left">Honda Civic</td>
<td align="center">30.4</td>
<td align="center">4</td>
<td align="center">75.7</td>
<td align="center">52</td>
</tr>
<tr class="even">
<td align="left">Lotus Europa</td>
<td align="center">30.4</td>
<td align="center">4</td>
<td align="center">95.1</td>
<td align="center">113</td>
</tr>
<tr class="odd">
<td align="left">Fiat X1-9</td>
<td align="center">27.3</td>
<td align="center">4</td>
<td align="center">79.0</td>
<td align="center">66</td>
</tr>
<tr class="even">
<td align="left">Porsche 914-2</td>
<td align="center">26.0</td>
<td align="center">4</td>
<td align="center">120.3</td>
<td align="center">91</td>
</tr>
</tbody>
</table>
</div>
<div id="correlation" class="section level2">
<h2>Correlation</h2>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="statistics-lab.html#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(mtcars<span class="sc">$</span>hp, mtcars<span class="sc">$</span>mpg)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  mtcars$hp and mtcars$mpg
## t = -6.7424, df = 30, p-value = 1.788e-07
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.8852686 -0.5860994
## sample estimates:
##        cor 
## -0.7761684</code></pre>
<p>This is a correlation test between horsepower and miles per gallon, from the <code>mtcars</code> data set. From this test, we see:</p>
<ul>
<li>p = 1.7878353^{-7}</li>
<li>cor = -0.7761684</li>
</ul>
<p>We can determine that there is a significant and strong negative correlation between horsepower and fuel economy.</p>
</div>
<div id="two-sample-t-test---x-by-y" class="section level2">
<h2>Two Sample T Test - X by Y</h2>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="statistics-lab.html#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(mtcars<span class="sc">$</span>mpg <span class="sc">~</span> mtcars<span class="sc">$</span>am)</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  mtcars$mpg by mtcars$am
## t = -3.7671, df = 18.332, p-value = 0.001374
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -11.280194  -3.209684
## sample estimates:
## mean in group 0 mean in group 1 
##        17.14737        24.39231</code></pre>
<p>This is a t test comparing mean miles per gallon across cars grouped by transmission type, from the <code>mtcars</code> data set. From this test, we see:</p>
<ul>
<li>p = 0.0013736</li>
<li>mean of a = 17.1473684</li>
<li>mean of m = 24.3923077</li>
</ul>
<p>We can determine that there is a significant difference between the mean mpg of cars, based on transmission type.</p>
</div>
<div id="two-sample-t-test---x-and-y" class="section level2">
<h2>Two Sample T Test - X and Y</h2>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="statistics-lab.html#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(mtcars<span class="sc">$</span>mpg[mtcars<span class="sc">$</span>am<span class="sc">==</span><span class="dv">0</span>], mtcars<span class="sc">$</span>mpg[mtcars<span class="sc">$</span>am<span class="sc">==</span><span class="dv">1</span>])</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  mtcars$mpg[mtcars$am == 0] and mtcars$mpg[mtcars$am == 1]
## t = -3.7671, df = 18.332, p-value = 0.001374
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -11.280194  -3.209684
## sample estimates:
## mean of x mean of y 
##  17.14737  24.39231</code></pre>
<p>This is a t test comparing mean miles per gallon across cars grouped by transmission type, from the <code>mtcars</code> data set. From this test, we see:</p>
<ul>
<li>p = 0.0013736</li>
<li>mean of a = 17.1473684</li>
<li>mean of m = 24.3923077</li>
</ul>
<p>We can determine that there is a significant difference between the mean mpg of cars, based on transmission type.</p>
</div>
<div id="one-sample-t-test---x-and-estimated-y" class="section level2">
<h2>One Sample T Test - X and estimated Y</h2>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="statistics-lab.html#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(mtcars<span class="sc">$</span>mpg, <span class="at">mu =</span> <span class="dv">20</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  mtcars$mpg
## t = 0.08506, df = 31, p-value = 0.9328
## alternative hypothesis: true mean is not equal to 20
## 95 percent confidence interval:
##  17.91768 22.26357
## sample estimates:
## mean of x 
##  20.09062</code></pre>
<p>This is a t test comparing mean miles per gallon, from the <code>mtcars</code> data set, compared to an estimated population mean. From this test, we see:</p>
<ul>
<li>p = 0.9327606</li>
<li>mean = 20.090625</li>
<li>mu (estimate) = 20</li>
</ul>
<p>We can determine that there is not a significant difference between the mean mpg of cars, and our hypothesized mean.</p>
</div>
<div id="chi-square---table-data" class="section level2">
<h2>Chi-Square - Table Data</h2>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="statistics-lab.html#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(mtcars<span class="sc">$</span>cyl, mtcars<span class="sc">$</span>am)</span></code></pre></div>
<pre><code>   
     0  1
  4  3  8
  6  4  3
  8 12  2</code></pre>
<p>This is a row by column table, used to evaluate the chi-squared test.
This table compares engine cylinders across cars grouped by transmission type, from the <code>mtcars</code> data set.
For this Chi-Square test, we are testing the independence of the two observed factors.
From this test, we should note:</p>
<ul>
<li>not every cell has at least 5 observations</li>
<li>our test approximation may be incorrect as a result</li>
</ul>
</div>
<div id="chi-square---x-and-y" class="section level2">
<h2>Chi-Square - X and Y</h2>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="statistics-lab.html#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(mtcars<span class="sc">$</span>cyl, mtcars<span class="sc">$</span>am)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  mtcars$cyl and mtcars$am
## X-squared = 8.7407, df = 2, p-value = 0.01265</code></pre>
<p>This is a chi-squared test comparing engine cylinders across cars grouped by transmission type, from the <code>mtcars</code> data set. This test was conducted using vectors. From this test, we see:</p>
<ul>
<li>p = 0.0126466</li>
</ul>
<p>We can determine that there is a significant difference between the distribution of cylinders across cars grouped by transmission type. We should reference the table to determine the differences.</p>
</div>
<div id="chi-square---table" class="section level2">
<h2>Chi-Square - Table</h2>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="statistics-lab.html#cb118-1" aria-hidden="true" tabindex="-1"></a>chitab <span class="ot">=</span> <span class="fu">table</span>(mtcars<span class="sc">$</span>cyl, mtcars<span class="sc">$</span>am)</span>
<span id="cb118-2"><a href="statistics-lab.html#cb118-2" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(chitab)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  chitab
## X-squared = 8.7407, df = 2, p-value = 0.01265</code></pre>
<p>This is a chi-squared test comparing engine cylinders across cars grouped by transmission type, from the <code>mtcars</code> data set. This test was conducted using a table. From this test, we see:</p>
<ul>
<li>p = 0.0126466</li>
</ul>
<p>We can determine that there is a significant difference between the distribution of cylinders across cars grouped by transmission type. We should reference the table to determine the differences.</p>
</div>
<div id="linear-model---y-by-x" class="section level2">
<h2>Linear Model - Y by X</h2>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="statistics-lab.html#cb120-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(mtcars<span class="sc">$</span>mpg <span class="sc">~</span> mtcars<span class="sc">$</span>hp))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mtcars$mpg ~ mtcars$hp)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.7121 -2.1122 -0.8854  1.5819  8.2360 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 30.09886    1.63392  18.421  &lt; 2e-16 ***
## mtcars$hp   -0.06823    0.01012  -6.742 1.79e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.863 on 30 degrees of freedom
## Multiple R-squared:  0.6024, Adjusted R-squared:  0.5892 
## F-statistic: 45.46 on 1 and 30 DF,  p-value: 1.788e-07</code></pre>
<p>This is a linear model of how horsepower predicts miles per gallon, from the <code>mtcars</code> data set. From this test, we see:</p>
<ul>
<li>B0 Estimate = 30.0988605</li>
<li>B1 Estimate = -0.0682283</li>
<li>B1 p = 1.7878353^{-7}</li>
<li>Adj R Square = 0.5891853</li>
</ul>
<p>We can determine that there is a significant negative linear relationship between fuel economy and engine horsepower. This model accounts for 58.9% of the observed change.</p>
</div>
<div id="linear-model---y-by-x-x" class="section level2">
<h2>Linear Model - Y by X + X</h2>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="statistics-lab.html#cb122-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(mtcars<span class="sc">$</span>mpg <span class="sc">~</span> mtcars<span class="sc">$</span>hp <span class="sc">+</span> mtcars<span class="sc">$</span>wt))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mtcars$mpg ~ mtcars$hp + mtcars$wt)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -3.941 -1.600 -0.182  1.050  5.854 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 37.22727    1.59879  23.285  &lt; 2e-16 ***
## mtcars$hp   -0.03177    0.00903  -3.519  0.00145 ** 
## mtcars$wt   -3.87783    0.63273  -6.129 1.12e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.593 on 29 degrees of freedom
## Multiple R-squared:  0.8268, Adjusted R-squared:  0.8148 
## F-statistic: 69.21 on 2 and 29 DF,  p-value: 9.109e-12</code></pre>
<!-- This is a linear model of how horsepower predicts miles per gallon, from the `mtcars` data set. From this test, we see: -->
<ul>
<li>B0 Estimate = 37.2272701</li>
<li>B1 Estimate = -0.0317729</li>
<li>B2 Estimate = -3.8778307</li>
<li>B1 p = 0.0014512</li>
<li>B2 p = 1.1196471^{-6}</li>
<li>Adj R Square = 0.8148396</li>
</ul>
<p>We can determine that there is a significant negative linear relationship between fuel economy and engine horsepower + vehicle weight. This model accounts for 81.5% of the observed change.</p>
</div>
<div id="linear-model---y-by-x-x-xx" class="section level2">
<h2>Linear Model - Y by X + X + X:X</h2>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="statistics-lab.html#cb124-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(mtcars<span class="sc">$</span>mpg <span class="sc">~</span> mtcars<span class="sc">$</span>hp <span class="sc">*</span> mtcars<span class="sc">$</span>wt))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mtcars$mpg ~ mtcars$hp * mtcars$wt)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.0632 -1.6491 -0.7362  1.4211  4.5513 
## 
## Coefficients:
##                     Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)         49.80842    3.60516  13.816 5.01e-14 ***
## mtcars$hp           -0.12010    0.02470  -4.863 4.04e-05 ***
## mtcars$wt           -8.21662    1.26971  -6.471 5.20e-07 ***
## mtcars$hp:mtcars$wt  0.02785    0.00742   3.753 0.000811 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.153 on 28 degrees of freedom
## Multiple R-squared:  0.8848, Adjusted R-squared:  0.8724 
## F-statistic: 71.66 on 3 and 28 DF,  p-value: 2.981e-13</code></pre>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="statistics-lab.html#cb126-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(mtcars<span class="sc">$</span>mpg <span class="sc">~</span> mtcars<span class="sc">$</span>hp <span class="sc">+</span> mtcars<span class="sc">$</span>wt <span class="sc">+</span> mtcars<span class="sc">$</span>hp<span class="sc">:</span>mtcars<span class="sc">$</span>wt))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mtcars$mpg ~ mtcars$hp + mtcars$wt + mtcars$hp:mtcars$wt)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.0632 -1.6491 -0.7362  1.4211  4.5513 
## 
## Coefficients:
##                     Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)         49.80842    3.60516  13.816 5.01e-14 ***
## mtcars$hp           -0.12010    0.02470  -4.863 4.04e-05 ***
## mtcars$wt           -8.21662    1.26971  -6.471 5.20e-07 ***
## mtcars$hp:mtcars$wt  0.02785    0.00742   3.753 0.000811 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.153 on 28 degrees of freedom
## Multiple R-squared:  0.8848, Adjusted R-squared:  0.8724 
## F-statistic: 71.66 on 3 and 28 DF,  p-value: 2.981e-13</code></pre>
<!-- This is a linear model of how horsepower predicts miles per gallon, from the `mtcars` data set. From this test, we see: -->
<ul>
<li>B0 Estimate = 49.8084234</li>
<li>B1 Estimate = -0.1201021</li>
<li>B2 Estimate = -8.2166243</li>
<li>B1:B2 Estimate = 0.0278481</li>
<li>B1 p = 4.036243^{-5}</li>
<li>B2 p = 5.1992873^{-7}</li>
<li>B1:B2 p = 8.1083074^{-4}</li>
<li>Adj R Square = 0.872417</li>
</ul>
<p>We can determine that there is a significant negative linear relationship between fuel economy and engine horsepower + vehicle weight + interaction. This model accounts for 87.2% of the observed change.</p>
</div>
<div id="anova---x-by-y" class="section level2">
<h2>ANOVA - X by Y</h2>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="statistics-lab.html#cb128-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(mtcars<span class="sc">$</span>mpg<span class="sc">~</span><span class="fu">as.factor</span>(mtcars<span class="sc">$</span>cyl)))</span></code></pre></div>
<pre><code>##                       Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## as.factor(mtcars$cyl)  2  824.8   412.4    39.7 4.98e-09 ***
## Residuals             29  301.3    10.4                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>This is an ANOVA test comparing mean miles per gallon across cars grouped by number of engine cylinders, from the <code>mtcars</code> data set. From this test, we see:</p>
<ul>
<li>p = 4.9789192^{-9}</li>
</ul>
<p>We can determine that there is a significant difference between the mean mpg of cars, based on number of engine cylinders. We do not yet know which groups are different.</p>
</div>
<div id="anova---multiple-comparisons" class="section level2">
<h2>ANOVA - Multiple Comparisons</h2>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="statistics-lab.html#cb130-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(<span class="fu">aov</span>(mtcars<span class="sc">$</span>mpg<span class="sc">~</span><span class="fu">as.factor</span>(mtcars<span class="sc">$</span>cyl)))</span></code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = mtcars$mpg ~ as.factor(mtcars$cyl))
## 
## $`as.factor(mtcars$cyl)`
##           diff        lwr        upr     p adj
## 6-4  -6.920779 -10.769350 -3.0722086 0.0003424
## 8-4 -11.563636 -14.770779 -8.3564942 0.0000000
## 8-6  -4.642857  -8.327583 -0.9581313 0.0112287</code></pre>
<p>This is a Tukey multiple comparisons test comparing the differences between observed groups from our significant ANOVA test. From this test, we see:</p>
<ul>
<li>P: 6-4 = 3.4237205^{-4}</li>
<li>P: 8-4 = 2.5439802^{-9}</li>
<li>P: 8-6 = 0.0112287</li>
</ul>
<p>We can determine that there is a significant difference between the mean mpg of cars, based on number of engine cylinders, across all observed groups.</p>
</div>
<div id="goals-7" class="section level2">
<h2>Goals</h2>
<p>At the end of the Lab, we have learned:</p>
<ul>
<li>How to pick a statistical test for your data</li>
<li>How to run statistical tests in R</li>
<li>How to interpret the results of statistical tests</li>
</ul>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="stats.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": false
},
"fontsettings": {
"theme": "white",
"family": "serif",
"size": 2
},
"edit": null,
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "lunr",
"options": null
},
"toc": {
"collapse": "subsection",
"scroll_highlight": true
},
"toolbar": {
"position": "fixed"
},
"info": true
});
});
</script>

</body>

</html>
